Algoritmo "Cronometro"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : Apresentar os resultados de uma tabuada.
// Autor(a)    : Gabriel Oliveira
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   contadora1, contadora2: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   
   para contadora1 de 0 ate 59 passo 1 faça
    para contadora2 de 0 ate 59 passo 1 faça
    escreva(contadora1," : ", contadora2)
      fimpara
   fimpara

Fimalgoritmo