Algoritmo "ExemploLacodeRepeticaoEnquanto"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : exemplo de execução do laço de repetição.
// Autor(a)    : Gabriel Oliveira
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   contadora: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto contadora <10 faça
      escreval("Olá, meu nome é Gabriel")
      contadora<- contadora+1
   fimenquanto

Fimalgoritmo