Algoritmo "ExemploTomadaDecisaoComposta"
// Disciplina  : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : Solicita que o usuario digite um valor e o computador
// tome uma decisão de acordo com o teste
// Autor(a)    : Gabriel Oliveira
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis 
 numero : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Programa de Tomada de Decisão Composta")
  escreval("Digite um valor")
 leia(numero)
 se numero > 10 então
 escreval("Número digitado é maior que 10")
 senao
 Escreval("Número digitado é menor que 10")
 fimse

Fimalgoritmo