Algoritmo "ExercicioLacoPara"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : Somatorio de graos exponecialmente em um quadro de xaderz.
// Autor(a)    : Gabriel Oliveira
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   contadora : inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para contadora de 1 ate 100 passo 10 faça
      escreval(contadora)
   fimpara

Fimalgoritmo