Algoritmo "Saudacao"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : Recebe o nome do usuario e envia uma mensagem de saudacao
// Autor(a)    : Gabriel Oliveira
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
 nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Digite seu nome: ")
  leia(nome)
  escreva("Bom dia ",nome)
Fimalgoritmo