Algoritmo "Subtracao"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : recebe dois numeros realiza a subtracao e mostra o resultado
// Autor(a)    : Gabrie Oliveira
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
  numero1: inteiro
  numero2: inteiro
  resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Digitar um numero: ")
  leia(numero1)
  escreval("Digitar mais um numero: ")
  leia(numero2)
  resultado<- numero1 - numero2
  escreval("O resultado da calculo é: ", resultado)

Fimalgoritmo