Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : Algoritmo que solicita um numero e mostra o antecessor desse numero.
// Autor(a)    : Gabriel Oliveira
// Data atual  : 19/03/2026
Var
// Seção de Declarações das variáveis 
  numero1: inteiro
  resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Digite um numero: ")
  leia(numero1)
  resultado<- numero1 - 1
  escreval("O numero antecessor e: ", resultado)

Fimalgoritmo