Algoritmo "AreadeCirculo"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : Recebe o valor do raio de um círculo, calcula a área e exibe o
// resultado
// Autor(a)    : Gabriel Oliveira
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
 raio, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Digite o valor do raio do círculo: ")
  leia(raio)

  area<- 3.14 * (raio*raio)
  escreva("Essa é a área do círculo: ", area)
Fimalgoritmo