Algoritmo "converta-metros-centimetros-versao2"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : solicita um valor em metros, converte para centimetros e mostra o resultado
// Autor(a)    : Gabriel Oliveira
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis 
 numero : real
 metros : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 metros <- 100
 escreval("Digiteum valor em metros")
 leia(numero)
 escreva("o resultado em centímetros é: ", numero*metros," centímetros")

Fimalgoritmo