Algoritmo "ExRepeticaoRepita"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : Teste da função repita
// até 500
// Autor(a)    : Gabriel Oliveira
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
    contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   repita
   escreval(contador)
   contador<- contador+1
   ate contador > 10



Fimalgoritmo