Algoritmo "FaixaCorreta"
// Disciplina  : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : EElaborar um programa que efetue a leitura de um valor que
// esteja entre a faixa de 1 a 9. Após a leitura do valor fornecido pelo usuário,
//  o programa deverá indicar uma de duas mensagens: "O valor está na faixa
// permitida", caso o usuário forneça o valor nesta faixa, ou a mensagem "O
// valor está fora da faixa permitida", caso o usuário forneça valores menores
// que 1 ou maiores que 9.
// Data atual  : 23/03/2026
Var
   // Seção de Declarações das variáveis

   numero: inteiro



Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite um número aleatório para ganhar um presente: ")
   leia(numero)
   escreval("")

   se (numero > 1 ) e (numero < 9 ) entao
      escreval("O valor está na faixa permitida")
   senao
      escreval("O valor está fora da faixa permitida")
      fimse

Fimalgoritmo