Algoritmo "ProdutoeSoma"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : Solicita valor de A, B, C e D calcula o produto de A com C, a
// soma de B com D, calcula o resultado e exibe o resultado..
// Autor(a)    : Gabriel Oliveira
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
 a, b, c, d, produto, soma: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Digite o número A: ")
  leia(a)
  escreva("Digite o número B: ")
  leia(b)
  escreva("Digite o número C: ")
  leia(c)
  escreva("Digite o número d: ")
  leia(d)
  
   produto<- a * c
   soma<- b + d

  
  escreval("O resultado do produto de A com C é: ",produto)
  escreval("O resultado da soma de B com D é: ",soma)



Fimalgoritmo