Algoritmo "SomaMulplicacao4"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa
// Descrição   : Solicita valor de A, B, C e D, realiza a soma e a multiplicação
// entre todas as combinações possíveis de quatro números inteiros e exibe os
// resultados.
// Autor(a)    : Gabriel Oliveira
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
 a, b, c, d, soma, multiplicacao: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("digite o valor de A: ")
  leia(a)
  escreva("Digite o valor de B:  ")
  leia(b)
  escreva("Digite o valor de C:  ")
  leia(c)
  escreva("Digite o valor de D:  ")
  leia(d)

  escreval("A + B =", a+b)
  escreval("A x B =", a*b)
  escreval("")
  
  escreval("A + C =", a+c)
  escreval("A x C =", a*c)
  escreval("")
  
  escreval("A + D =", a+d)
  escreval("A x D =", a*d)
  escreval("")
  
  escreval("B + C =", b+c)
  escreval("B x C =", b*c)
  escreval("")
  
  escreval("B + D =", b+d)
  escreval("B x D =", b*d)
  escreval("")
  
  escreval("C + D =", c+d)
  escreval("C x D =", c*d)
  escreval("")
  


Fimalgoritmo